/**
 * Database schema for FusionPrints.
 *
 * This file defines every table in the database. Drizzle reads it to:
 *   1. Generate SQL migrations (npm run db:migrate)
 *   2. Provide type-safe query building from TypeScript
 *
 * Conventions:
 *   - All tables have a UUID primary key generated by Postgres
 *   - All money is NUMERIC, never float
 *   - All timestamps are TIMESTAMPTZ (timezone-aware)
 *   - JSONB for flexible/varying data (bot context, webhook payloads)
 *
 * When you change this file, run: npm run db:migrate
 */

import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  numeric,
  boolean,
  jsonb,
  bigint,
  pgEnum,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

// ===== Enums =====

export const orderStatusEnum = pgEnum('order_status', [
  'pending_payment',
  'paid',
  'awaiting_approval', // posters need human review before printing
  'queued_for_print',
  'printing',
  'printed',           // all print jobs done; awaiting operator release for pickup
  'ready_for_pickup',  // operator has released; customer notified
  'ready_for_collection', // legacy — preserved for backward compat
  'shipped', // delivery orders that have left the shop
  'fulfilled',
  'cancelled',
  'failed',
]);

export const fulfillmentMethodEnum = pgEnum('fulfillment_method', [
  'collection',
  'delivery',
]);

// Which channel an order came through. Defaults to 'whatsapp' so existing rows
// and the WhatsApp flow are unaffected; web (self-serve) orders set 'web'.
export const orderChannelEnum = pgEnum('order_channel', ['whatsapp', 'web']);

export const productTypeEnum = pgEnum('product_type', ['photo_print', 'poster']);

export const paymentStatusEnum = pgEnum('payment_status', [
  'pending',
  'success',
  'failed',
  'cancelled',
]);

export const paymentProviderEnum = pgEnum('payment_provider', [
  'paynow',
  'flutterwave',
  'virtual', // service-virtualised provider (web checkout) until a real gateway is live
]);

export const printJobStatusEnum = pgEnum('print_job_status', [
  'queued',
  'awaiting_approval',
  'printing',
  'done',
  'failed',
]);

export const printerTypeEnum = pgEnum('printer_type', ['dye_sub', 'inkjet']);

export const printerStatusEnum = pgEnum('printer_status', [
  'online',
  'offline',
  'media_low',
  'error',
]);

// New for Phase D — multi-printer routing target.
// Each print job is tagged with which TYPE of printer should handle it.
// The agent fetches only jobs matching its configured printer_type.
export const targetPrinterTypeEnum = pgEnum('target_printer_type', [
  'dye_sub_4x6',     // DNP #1 with 6×8 master media (handles 4×6, 6×6, 6×8)
  'dye_sub_5x7',     // DNP #2 with 5×7 media
  'inkjet',          // Epson SC-P900 (handles 8×10, 11×14, 12×18, 16×20)
  'thermal_label',   // Zebra/Xprinter for envelope labels
]);

// New for Phase D — slip jobs are operational/branded prints, separate from customer prints.
export const slipTypeEnum = pgEnum('slip_type', [
  'order_info',      // 4×6 dye-sub card with order details (top of stack)
  'end_separator',   // 4×6 dye-sub card with brand moment (bottom of stack)
  'envelope_label',  // 2-1/4×4 thermal sticker for envelope exterior
]);

// ===== Tables =====

/**
 * Customers — identified by their WhatsApp phone number.
 * One customer can have many orders.
 */
export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    phoneNumber: text('phone_number').notNull(), // E.164 format: +263771234567
    name: text('name'), // collected on first order
    email: text('email'), // optional
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastOrderAt: timestamp('last_order_at', { withTimezone: true }),
  },
  (table) => ({
    phoneIdx: uniqueIndex('customers_phone_idx').on(table.phoneNumber),
  }),
);

/**
 * Conversation state — the bot's memory for each customer.
 * Holds where they are in the order flow and any pending data.
 * One row per customer (1:1 with customers).
 */
export const conversationState = pgTable('conversation_state', {
  customerId: uuid('customer_id')
    .primaryKey()
    .references(() => customers.id, { onDelete: 'cascade' }),
  currentStep: text('current_step').notNull().default('idle'),
  context: jsonb('context').notNull().default({}), // working memory — current cart, pending image, etc.
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Images — uploaded by customers (WhatsApp) or web platform users.
 * Stored externally (Backblaze B2); this table holds metadata + URL.
 *
 * Polymorphic owner: exactly ONE of customerId / webUserId is set.
 *   - customerId set  → uploaded via WhatsApp (30-day retention)
 *   - webUserId  set  → uploaded via the web platform (90-day retention)
 * Enforced in application logic; both are nullable at the DB level so the
 * same table (and order_items/images relation) is shared across channels.
 *
 * Auto-deleted after its retention window via a scheduled job.
 */
export const images = pgTable(
  'images',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customerId: uuid('customer_id').references(() => customers.id, {
      onDelete: 'cascade',
    }),
    webUserId: uuid('web_user_id').references(() => webUsers.id, {
      onDelete: 'cascade',
    }),
    storageUrl: text('storage_url').notNull(),
    storageKey: text('storage_key').notNull(), // path within bucket, for deletion
    originalFilename: text('original_filename'),
    widthPx: integer('width_px'),
    heightPx: integer('height_px'),
    fileSizeBytes: bigint('file_size_bytes', { mode: 'number' }),
    format: text('format'), // 'jpeg', 'png', 'tiff', etc.
    wasCompressed: boolean('was_compressed').notNull().default(false),
    uploadedAt: timestamp('uploaded_at', { withTimezone: true }).notNull().defaultNow(),
    deleteAfter: timestamp('delete_after', { withTimezone: true }),
  },
  (table) => ({
    customerIdx: index('images_customer_idx').on(table.customerId),
    webUserIdx: index('images_web_user_idx').on(table.webUserId),
    deleteAfterIdx: index('images_delete_after_idx').on(table.deleteAfter),
  }),
);

/**
 * Orders — the unit a customer pays for.
 * Contains 1+ order_items.
 */
export const orders = pgTable(
  'orders',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    // Nullable now: WhatsApp orders set customerId; web orders set webUserId.
    customerId: uuid('customer_id').references(() => customers.id),
    webUserId: uuid('web_user_id').references(() => webUsers.id),
    channel: orderChannelEnum('channel').notNull().default('whatsapp'),
    orderNumber: text('order_number').notNull(), // human-friendly: 'FP-2026-0042'
    status: orderStatusEnum('status').notNull().default('pending_payment'),
    subtotalUsd: numeric('subtotal_usd', { precision: 10, scale: 2 }).notNull(),
    deliveryFeeUsd: numeric('delivery_fee_usd', { precision: 10, scale: 2 })
      .notNull()
      .default('0'),
    totalUsd: numeric('total_usd', { precision: 10, scale: 2 }).notNull(),
    fulfillmentMethod: fulfillmentMethodEnum('fulfillment_method').notNull(),
    deliveryAddress: text('delivery_address'),
    notes: text('notes'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    paidAt: timestamp('paid_at', { withTimezone: true }),
    readyAt: timestamp('ready_at', { withTimezone: true }),
    shippedAt: timestamp('shipped_at', { withTimezone: true }),
    fulfilledAt: timestamp('fulfilled_at', { withTimezone: true }),
    receiptSentAt: timestamp('receipt_sent_at', { withTimezone: true }),
  },
  (table) => ({
    orderNumberIdx: uniqueIndex('orders_order_number_idx').on(table.orderNumber),
    customerIdx: index('orders_customer_idx').on(table.customerId),
    webUserIdx: index('orders_web_user_idx').on(table.webUserId),
    statusIdx: index('orders_status_idx').on(table.status),
    createdAtIdx: index('orders_created_at_idx').on(table.createdAt),
  }),
);

/**
 * Order items — individual prints within an order.
 * Snapshots the price at order time so historical orders are immutable.
 */
export const orderItems = pgTable(
  'order_items',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    // Source image. Nullable now: web items reference the edited render via
    // processedImageId; imageId carries the original source image when known.
    // SET NULL on delete so a customer can remove a photo without the FK
    // blocking it — the order record (price/size snapshot) is preserved.
    imageId: uuid('image_id').references(() => images.id, { onDelete: 'set null' }),
    // Web (edited) items point at the print-ready render the editor produced.
    processedImageId: uuid('processed_image_id').references(() => processedImages.id, { onDelete: 'set null' }),
    productType: productTypeEnum('product_type').notNull(),
    sizeCode: text('size_code').notNull(), // '4x6', '5x7', '11x14', etc.
    paper: text('paper'), // finish chosen on web ('glossy' | 'satin'); null = product default
    quantity: integer('quantity').notNull().default(1),
    unitPriceUsd: numeric('unit_price_usd', { precision: 10, scale: 2 }).notNull(),
    lineTotalUsd: numeric('line_total_usd', { precision: 10, scale: 2 }).notNull(),
    requiresManualReview: boolean('requires_manual_review').notNull().default(false),
  },
  (table) => ({
    orderIdx: index('order_items_order_idx').on(table.orderId),
    processedImageIdx: index('order_items_processed_image_idx').on(table.processedImageId),
  }),
);

/**
 * Payments — one order can have multiple attempts (e.g., retry after fail).
 * Webhook payload is kept for debugging disputes.
 */
export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id),
    provider: paymentProviderEnum('provider').notNull(),
    providerReference: text('provider_reference'), // their transaction ID
    amountUsd: numeric('amount_usd', { precision: 10, scale: 2 }).notNull(),
    status: paymentStatusEnum('status').notNull().default('pending'),
    paymentMethod: text('payment_method'), // 'ecocash', 'card', etc.
    initiatedAt: timestamp('initiated_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    webhookPayload: jsonb('webhook_payload'), // raw payload for debugging
  },
  (table) => ({
    orderIdx: index('payments_order_idx').on(table.orderId),
    providerRefIdx: index('payments_provider_ref_idx').on(table.providerReference),
  }),
);

/**
 * Printers — registered devices the print agent dispatches to.
 * Phase 1: 2 rows (DNP DS620A and Epson P900).
 */
export const printers = pgTable('printers', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(), // 'DNP DS620A'
  printerType: printerTypeEnum('printer_type').notNull(),
  osPrinterName: text('os_printer_name').notNull(), // name as the OS sees it
  currentMedia: text('current_media'), // '6x8 ribbon', '17in luster roll'
  status: printerStatusEnum('status').notNull().default('online'),
  lastHeartbeatAt: timestamp('last_heartbeat_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Print jobs — what the print agent picks up and produces.
 * One per order_item.
 */
export const printJobs = pgTable(
  'print_jobs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orderItemId: uuid('order_item_id')
      .notNull()
      .references(() => orderItems.id, { onDelete: 'cascade' }),
    printerId: uuid('printer_id').references(() => printers.id),
    // Phase D: which type of printer should handle this job.
    // Nullable so existing rows (pre-D.1 deploy) remain valid.
    // Code defaults to dye_sub_4x6 if null (matches old single-DNP routing).
    targetPrinterType: targetPrinterTypeEnum('target_printer_type'),
    status: printJobStatusEnum('status').notNull().default('queued'),
    printReadyFileUrl: text('print_ready_file_url'), // prepared TIFF/PDF
    attempts: integer('attempts').notNull().default(0),
    errorMessage: text('error_message'),
    queuedAt: timestamp('queued_at', { withTimezone: true }).notNull().defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (table) => ({
    statusIdx: index('print_jobs_status_idx').on(table.status),
    orderItemIdx: index('print_jobs_order_item_idx').on(table.orderItemId),
    targetPrinterIdx: index('print_jobs_target_printer_idx').on(table.targetPrinterType),
  }),
);

/**
 * Slip jobs — operational/branded prints that accompany every order.
 *
 * Three types per order:
 *   1. order_info    — 4×6 dye-sub card, printed LAST (lands on top of stack inside envelope)
 *   2. end_separator — 4×6 dye-sub card, printed FIRST (lands at bottom of stack inside envelope)
 *   3. envelope_label — 2-1/4×4 thermal sticker, applied to OUTSIDE of envelope
 *
 * sequence_position controls print order within the same printer:
 *   0   = end_separator (prints first)
 *   100 = order_info    (prints last)
 *   N/A = envelope_label (different printer, no sequencing concern)
 */
export const slipJobs = pgTable(
  'slip_jobs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    printerId: uuid('printer_id').references(() => printers.id),
    slipType: slipTypeEnum('slip_type').notNull(),
    targetPrinterType: targetPrinterTypeEnum('target_printer_type').notNull(),
    sequencePosition: integer('sequence_position').notNull().default(50),
    status: printJobStatusEnum('status').notNull().default('queued'),
    printReadyFileUrl: text('print_ready_file_url'),
    payloadJson: jsonb('payload_json'), // for ZPL string or rendered slip data
    attempts: integer('attempts').notNull().default(0),
    errorMessage: text('error_message'),
    queuedAt: timestamp('queued_at', { withTimezone: true }).notNull().defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (table) => ({
    statusIdx: index('slip_jobs_status_idx').on(table.status),
    orderIdx: index('slip_jobs_order_idx').on(table.orderId),
    targetPrinterIdx: index('slip_jobs_target_printer_idx').on(table.targetPrinterType),
    sequenceIdx: index('slip_jobs_sequence_idx').on(table.orderId, table.sequencePosition),
  }),
);

// ===== Type exports for use throughout the app =====

export type Customer = typeof customers.$inferSelect;
export type NewCustomer = typeof customers.$inferInsert;

export type Order = typeof orders.$inferSelect;
export type NewOrder = typeof orders.$inferInsert;

export type OrderItem = typeof orderItems.$inferSelect;
export type NewOrderItem = typeof orderItems.$inferInsert;

export type Image = typeof images.$inferSelect;
export type NewImage = typeof images.$inferInsert;

export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;

export type PrintJob = typeof printJobs.$inferSelect;
export type NewPrintJob = typeof printJobs.$inferInsert;

export type SlipJob = typeof slipJobs.$inferSelect;
export type NewSlipJob = typeof slipJobs.$inferInsert;

export type Printer = typeof printers.$inferSelect;
export type NewPrinter = typeof printers.$inferInsert;

export type ConversationState = typeof conversationState.$inferSelect;
export type NewConversationState = typeof conversationState.$inferInsert;

// ===== Upload Sessions =====

/**
 * Web upload sessions.
 *
 * When a customer chooses the bulk upload option in the bot, we generate
 * a unique token that grants them access to a web upload page. They drag
 * and drop their photos, which upload directly to B2. When done, they
 * type UPLOADED in WhatsApp and the bot pulls in the images.
 *
 * Token is short and URL-safe. Sessions expire after 1 hour for security.
 */
export const uploadSessions = pgTable(
  'upload_sessions',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    token: text('token').notNull().unique(),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    sizeCode: text('size_code').notNull(), // e.g. '4x6'
    status: text('status').notNull().default('active'), // 'active' | 'completed' | 'expired'
    imageCount: integer('image_count').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (table) => ({
    tokenIdx: uniqueIndex('upload_sessions_token_idx').on(table.token),
    customerIdx: index('upload_sessions_customer_idx').on(table.customerId),
  }),
);

export type UploadSession = typeof uploadSessions.$inferSelect;
export type NewUploadSession = typeof uploadSessions.$inferInsert;

// ===== Site Visits (landing page tracking) =====

export const siteVisits = pgTable(
  'site_visits',
  {
    id:        uuid('id').primaryKey().defaultRandom(),
    visitedAt: timestamp('visited_at', { withTimezone: true }).notNull().defaultNow(),
    referrer:  text('referrer'),
    userAgent: text('user_agent'),
    ipHash:    text('ip_hash'),
  },
  (table) => ({
    visitedAtIdx: index('site_visits_visited_at_idx').on(table.visitedAt),
  }),
);

export type SiteVisit = typeof siteVisits.$inferSelect;

// ===== Waitlist =====

export const waitlist = pgTable(
  'waitlist',
  {
    id:          uuid('id').primaryKey().defaultRandom(),
    name:        text('name').notNull(),
    whatsapp:    text('whatsapp').notNull(),
    createdAt:   timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    notifiedAt:  timestamp('notified_at', { withTimezone: true }),
  },
  (table) => ({
    whatsappIdx: uniqueIndex('waitlist_whatsapp_idx').on(table.whatsapp),
  }),
);

export type Waitlist = typeof waitlist.$inferSelect;

// ===== Web Platform Users =====

/**
 * Web platform accounts — separate from WhatsApp customers.
 * Created when a user signs up via the web platform.
 * Optionally linked to an existing WhatsApp customer via whatsappNumber.
 *
 * Accounts are either password-based (signup) or Google-based (OAuth):
 * exactly one of passwordHash / googleId is set. This is enforced in app
 * logic (no DB CHECK) — see src/routes/web/auth.ts + google-auth.ts.
 * A password account can later be auto-linked to Google on the same email,
 * at which point both may be set.
 */
export const webUsers = pgTable(
  'web_users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: text('email').notNull(),
    passwordHash: text('password_hash'), // nullable — null for Google-only accounts
    googleId: text('google_id'), // Google "sub" claim — null for password-only accounts
    displayName: text('display_name'), // from Google profile, optional
    avatarUrl: text('avatar_url'), // Google profile picture, optional
    emailVerified: boolean('email_verified').notNull().default(false),
    emailVerificationToken: text('email_verification_token'),
    emailVerificationExpiresAt: timestamp('email_verification_expires_at', {
      withTimezone: true,
    }),
    whatsappNumber: text('whatsapp_number'), // optional E.164, links to WA customer
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  },
  (table) => ({
    emailIdx: uniqueIndex('web_users_email_idx').on(table.email),
    // Postgres treats NULLs as distinct, so many password-only users with
    // NULL google_id coexist under this unique index.
    googleIdIdx: uniqueIndex('web_users_google_id_idx').on(table.googleId),
    verificationTokenIdx: index('web_users_verification_token_idx').on(
      table.emailVerificationToken,
    ),
  }),
);

export type WebUser = typeof webUsers.$inferSelect;
export type NewWebUser = typeof webUsers.$inferInsert;

/**
 * Edited, print-ready renders produced by the web editor (Phase 2.2).
 * One source image can have many processed renders (different sizes/crops/
 * filters), so this is a child of `images`. The edit payload is stored so a
 * render can be reproduced or re-edited. Keyed uniquely by storage key (a hash
 * of the payload) so re-applying the same edit overwrites the same object.
 */
export const processedImages = pgTable(
  'processed_images',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    sourceImageId: uuid('source_image_id')
      .notNull()
      .references(() => images.id, { onDelete: 'cascade' }),
    webUserId: uuid('web_user_id')
      .notNull()
      .references(() => webUsers.id, { onDelete: 'cascade' }),
    sizeCode: text('size_code').notNull(),
    editPayload: jsonb('edit_payload').notNull(),
    processedStorageKey: text('processed_storage_key').notNull(),
    processedStorageUrl: text('processed_storage_url').notNull(),
    widthPx: integer('width_px').notNull(),
    heightPx: integer('height_px').notNull(),
    format: text('format').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    deleteAfter: timestamp('delete_after', { withTimezone: true }),
  },
  (table) => ({
    sourceIdx: index('processed_images_source_idx').on(table.sourceImageId),
    webUserIdx: index('processed_images_web_user_idx').on(table.webUserId),
    keyIdx: uniqueIndex('processed_images_key_idx').on(table.processedStorageKey),
  }),
);

export type ProcessedImage = typeof processedImages.$inferSelect;

// ===== Customer Addresses (web platform) =====

/**
 * Delivery addresses for web platform users.
 * Zimbabwe addresses are semi-structured — suburb + city + instructions
 * matter more than strict postal codes.
 */
export const customerAddresses = pgTable(
  'customer_addresses',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    webUserId: uuid('web_user_id')
      .notNull()
      .references(() => webUsers.id, { onDelete: 'cascade' }),
    label: text('label').notNull().default('Home'), // 'Home', 'Office', etc.
    recipientName: text('recipient_name').notNull(),
    addressLine1: text('address_line1').notNull(),
    suburb: text('suburb'),
    city: text('city').notNull(),
    deliveryInstructions: text('delivery_instructions'),
    isDefault: boolean('is_default').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    webUserIdx: index('customer_addresses_web_user_idx').on(table.webUserId),
  }),
);

export type CustomerAddress = typeof customerAddresses.$inferSelect;
export type NewCustomerAddress = typeof customerAddresses.$inferInsert;

/**
 * Persistent web session store (@fastify/session backend).
 *
 * Sessions were previously kept in the default in-memory store, so every
 * backend restart (each deploy, crash, or reboot) silently logged every user
 * out regardless of the cookie lifetime. Persisting them here means a session
 * lasts its full cookie lifetime across restarts.
 *
 *   sid    — the session id (cookie value)
 *   sess   — the serialized session object
 *   expire — when the row may be evicted; indexed for cheap sweeping
 */
export const webSessions = pgTable(
  'web_sessions',
  {
    sid: text('sid').primaryKey(),
    sess: jsonb('sess').notNull(),
    expire: timestamp('expire', { withTimezone: true }).notNull(),
  },
  (table) => ({
    expireIdx: index('web_sessions_expire_idx').on(table.expire),
  }),
);

export type WebSession = typeof webSessions.$inferSelect;
export type NewWebSession = typeof webSessions.$inferInsert;
