/**
 * Database schema for FusionPrints.
 *
 * This file defines every table in the database. Drizzle reads it to:
 *   1. Generate SQL migrations (npm run db:migrate)
 *   2. Provide type-safe query building from TypeScript
 *
 * Conventions:
 *   - All tables have a UUID primary key generated by Postgres
 *   - All money is NUMERIC, never float
 *   - All timestamps are TIMESTAMPTZ (timezone-aware)
 *   - JSONB for flexible/varying data (bot context, webhook payloads)
 *
 * When you change this file, run: npm run db:migrate
 */

import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  numeric,
  boolean,
  jsonb,
  bigint,
  pgEnum,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

// ===== Enums =====

export const orderStatusEnum = pgEnum('order_status', [
  'pending_payment',
  'paid',
  'awaiting_approval', // posters need human review before printing
  'queued_for_print',
  'printing',
  'ready_for_collection',
  'shipped', // delivery orders that have left the shop
  'fulfilled',
  'cancelled',
  'failed',
]);

export const fulfillmentMethodEnum = pgEnum('fulfillment_method', [
  'collection',
  'delivery',
]);

export const productTypeEnum = pgEnum('product_type', ['photo_print', 'poster']);

export const paymentStatusEnum = pgEnum('payment_status', [
  'pending',
  'success',
  'failed',
  'cancelled',
]);

export const paymentProviderEnum = pgEnum('payment_provider', [
  'paynow',
  'flutterwave',
]);

export const printJobStatusEnum = pgEnum('print_job_status', [
  'queued',
  'awaiting_approval',
  'printing',
  'done',
  'failed',
]);

export const printerTypeEnum = pgEnum('printer_type', ['dye_sub', 'inkjet']);

export const printerStatusEnum = pgEnum('printer_status', [
  'online',
  'offline',
  'media_low',
  'error',
]);

// ===== Tables =====

/**
 * Customers — identified by their WhatsApp phone number.
 * One customer can have many orders.
 */
export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    phoneNumber: text('phone_number').notNull(), // E.164 format: +263771234567
    name: text('name'), // collected on first order
    email: text('email'), // optional
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastOrderAt: timestamp('last_order_at', { withTimezone: true }),
  },
  (table) => ({
    phoneIdx: uniqueIndex('customers_phone_idx').on(table.phoneNumber),
  }),
);

/**
 * Conversation state — the bot's memory for each customer.
 * Holds where they are in the order flow and any pending data.
 * One row per customer (1:1 with customers).
 */
export const conversationState = pgTable('conversation_state', {
  customerId: uuid('customer_id')
    .primaryKey()
    .references(() => customers.id, { onDelete: 'cascade' }),
  currentStep: text('current_step').notNull().default('idle'),
  context: jsonb('context').notNull().default({}), // working memory — current cart, pending image, etc.
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Images — uploaded by customers.
 * Stored externally (Backblaze B2); this table holds metadata + URL.
 * Auto-deleted 30 days after fulfillment via a scheduled job.
 */
export const images = pgTable(
  'images',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    storageUrl: text('storage_url').notNull(),
    storageKey: text('storage_key').notNull(), // path within bucket, for deletion
    originalFilename: text('original_filename'),
    widthPx: integer('width_px'),
    heightPx: integer('height_px'),
    fileSizeBytes: bigint('file_size_bytes', { mode: 'number' }),
    format: text('format'), // 'jpeg', 'png', 'tiff', etc.
    wasCompressed: boolean('was_compressed').notNull().default(false),
    uploadedAt: timestamp('uploaded_at', { withTimezone: true }).notNull().defaultNow(),
    deleteAfter: timestamp('delete_after', { withTimezone: true }),
  },
  (table) => ({
    customerIdx: index('images_customer_idx').on(table.customerId),
    deleteAfterIdx: index('images_delete_after_idx').on(table.deleteAfter),
  }),
);

/**
 * Orders — the unit a customer pays for.
 * Contains 1+ order_items.
 */
export const orders = pgTable(
  'orders',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id),
    orderNumber: text('order_number').notNull(), // human-friendly: 'FP-2026-0042'
    status: orderStatusEnum('status').notNull().default('pending_payment'),
    subtotalUsd: numeric('subtotal_usd', { precision: 10, scale: 2 }).notNull(),
    deliveryFeeUsd: numeric('delivery_fee_usd', { precision: 10, scale: 2 })
      .notNull()
      .default('0'),
    totalUsd: numeric('total_usd', { precision: 10, scale: 2 }).notNull(),
    fulfillmentMethod: fulfillmentMethodEnum('fulfillment_method').notNull(),
    deliveryAddress: text('delivery_address'),
    notes: text('notes'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    paidAt: timestamp('paid_at', { withTimezone: true }),
    readyAt: timestamp('ready_at', { withTimezone: true }),
    shippedAt: timestamp('shipped_at', { withTimezone: true }),
    fulfilledAt: timestamp('fulfilled_at', { withTimezone: true }),
    receiptSentAt: timestamp('receipt_sent_at', { withTimezone: true }),
  },
  (table) => ({
    orderNumberIdx: uniqueIndex('orders_order_number_idx').on(table.orderNumber),
    customerIdx: index('orders_customer_idx').on(table.customerId),
    statusIdx: index('orders_status_idx').on(table.status),
    createdAtIdx: index('orders_created_at_idx').on(table.createdAt),
  }),
);

/**
 * Order items — individual prints within an order.
 * Snapshots the price at order time so historical orders are immutable.
 */
export const orderItems = pgTable(
  'order_items',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    imageId: uuid('image_id')
      .notNull()
      .references(() => images.id),
    productType: productTypeEnum('product_type').notNull(),
    sizeCode: text('size_code').notNull(), // '4x6', '5x7', '11x14', etc.
    quantity: integer('quantity').notNull().default(1),
    unitPriceUsd: numeric('unit_price_usd', { precision: 10, scale: 2 }).notNull(),
    lineTotalUsd: numeric('line_total_usd', { precision: 10, scale: 2 }).notNull(),
    requiresManualReview: boolean('requires_manual_review').notNull().default(false),
  },
  (table) => ({
    orderIdx: index('order_items_order_idx').on(table.orderId),
  }),
);

/**
 * Payments — one order can have multiple attempts (e.g., retry after fail).
 * Webhook payload is kept for debugging disputes.
 */
export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id),
    provider: paymentProviderEnum('provider').notNull(),
    providerReference: text('provider_reference'), // their transaction ID
    amountUsd: numeric('amount_usd', { precision: 10, scale: 2 }).notNull(),
    status: paymentStatusEnum('status').notNull().default('pending'),
    paymentMethod: text('payment_method'), // 'ecocash', 'card', etc.
    initiatedAt: timestamp('initiated_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    webhookPayload: jsonb('webhook_payload'), // raw payload for debugging
  },
  (table) => ({
    orderIdx: index('payments_order_idx').on(table.orderId),
    providerRefIdx: index('payments_provider_ref_idx').on(table.providerReference),
  }),
);

/**
 * Printers — registered devices the print agent dispatches to.
 * Phase 1: 2 rows (DNP DS620A and Epson P900).
 */
export const printers = pgTable('printers', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(), // 'DNP DS620A'
  printerType: printerTypeEnum('printer_type').notNull(),
  osPrinterName: text('os_printer_name').notNull(), // name as the OS sees it
  currentMedia: text('current_media'), // '6x8 ribbon', '17in luster roll'
  status: printerStatusEnum('status').notNull().default('online'),
  lastHeartbeatAt: timestamp('last_heartbeat_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Print jobs — what the print agent picks up and produces.
 * One per order_item.
 */
export const printJobs = pgTable(
  'print_jobs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orderItemId: uuid('order_item_id')
      .notNull()
      .references(() => orderItems.id, { onDelete: 'cascade' }),
    printerId: uuid('printer_id').references(() => printers.id),
    status: printJobStatusEnum('status').notNull().default('queued'),
    printReadyFileUrl: text('print_ready_file_url'), // prepared TIFF/PDF
    attempts: integer('attempts').notNull().default(0),
    errorMessage: text('error_message'),
    queuedAt: timestamp('queued_at', { withTimezone: true }).notNull().defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (table) => ({
    statusIdx: index('print_jobs_status_idx').on(table.status),
    orderItemIdx: index('print_jobs_order_item_idx').on(table.orderItemId),
  }),
);

// ===== Type exports for use throughout the app =====

export type Customer = typeof customers.$inferSelect;
export type NewCustomer = typeof customers.$inferInsert;

export type Order = typeof orders.$inferSelect;
export type NewOrder = typeof orders.$inferInsert;

export type OrderItem = typeof orderItems.$inferSelect;
export type NewOrderItem = typeof orderItems.$inferInsert;

export type Image = typeof images.$inferSelect;
export type NewImage = typeof images.$inferInsert;

export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;

export type PrintJob = typeof printJobs.$inferSelect;
export type NewPrintJob = typeof printJobs.$inferInsert;

export type Printer = typeof printers.$inferSelect;
export type NewPrinter = typeof printers.$inferInsert;

export type ConversationState = typeof conversationState.$inferSelect;
export type NewConversationState = typeof conversationState.$inferInsert;

// ===== Upload Sessions =====

/**
 * Web upload sessions.
 *
 * When a customer chooses the bulk upload option in the bot, we generate
 * a unique token that grants them access to a web upload page. They drag
 * and drop their photos, which upload directly to B2. When done, they
 * type UPLOADED in WhatsApp and the bot pulls in the images.
 *
 * Token is short and URL-safe. Sessions expire after 1 hour for security.
 */
export const uploadSessions = pgTable(
  'upload_sessions',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    token: text('token').notNull().unique(),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    sizeCode: text('size_code').notNull(), // e.g. '4x6'
    status: text('status').notNull().default('active'), // 'active' | 'completed' | 'expired'
    imageCount: integer('image_count').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (table) => ({
    tokenIdx: uniqueIndex('upload_sessions_token_idx').on(table.token),
    customerIdx: index('upload_sessions_customer_idx').on(table.customerId),
  }),
);

export type UploadSession = typeof uploadSessions.$inferSelect;
export type NewUploadSession = typeof uploadSessions.$inferInsert;
